name: Build extension
permissions:
  id-token: write
  attestations: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    uses: FriendsOfShopware/actions/.github/workflows/store-shoxpware-cli.yml@main
    with:
      extensionName: NuonicPaymentMethodSurcharge
    secrets:
      accountUser: ${{ secrets.SHOPWARE_ACCOUNT_MACHINE_USER }}
      accountPassword: ${{ secrets.SHOPWARE_ACCOUNT_MACHINE_PASSWORD }}
      ghToken: ${{ secrets.GITHUB_TOKEN }}

  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: 'NuonicPaymentMethodSurcharge'
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'NuonicPaymentMethodSurcharge.zip'
